<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tarifa\Commands\**" />
    <EmbeddedResource Remove="Tarifa\Commands\**" />
    <None Remove="Tarifa\Commands\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VUCE3.Catalogos.Dominio\VUCE3.Catalogos.Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Moneda\Commands\" />
  </ItemGroup>

</Project>
