// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VUCE3.Catalogos.Infraestructura.Persistencia;

#nullable disable

namespace VUCE3.Catalogos.Infraestructura.Migrations
{
    [DbContext(typeof(CatalogosDbContext))]
    partial class CatalogosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Aduana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeclarationOffice");

                    b.HasKey("Id");

                    b.ToTable("Aduanas", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Barrio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("Street and number/P.O. Box-CB");

                    b.Property<int>("IdDistrito")
                        .HasColumnType("int")
                        .HasColumnName("City name");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Street and number/P.O. Box");

                    b.HasKey("Id");

                    b.HasIndex("IdDistrito");

                    b.ToTable("Barrios", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.BloqueComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("BloquesComerciales", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Canton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Country sub-entity identification code-CC");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int")
                        .HasColumnName("Country sub-entity name");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Country sub-entity identification code");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Cantones", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int")
                        .HasColumnName("Responsible government agency identifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Commodity characteristics description");

                    b.HasKey("Id");

                    b.ToTable("Caracteristicas", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.CaracteristicaTipoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCaracteristica")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCaracteristica");

                    b.HasIndex("IdTipoProducto");

                    b.ToTable("CaracteristicaTipoProducto", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Casa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("StatementCode");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StatementDescription");

                    b.HasKey("Id");

                    b.ToTable("Casas", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionControlador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdFuncionalidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreIngles")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreInglesNormalizado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiereFirma")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibleEmpresa")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Catalogos", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.CatalogoInstitucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogoId")
                        .HasColumnType("int");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.ToTable("CatalogosInstituciones", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int")
                        .HasColumnName("Responsible government agency identifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Intended use statement");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("Identifier");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Document expiration date/time");

                    b.Property<string>("IdTipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("IdentificationScheme.Identifier");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Master data party name");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Master data party identifier");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Cultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Product identifier");

                    b.Property<int>("IdVariedad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Commodity characteristics description");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Commodity classification name code");

                    b.HasKey("Id");

                    b.HasIndex("IdVariedad");

                    b.ToTable("Cultivos", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("City name-CD");

                    b.Property<int>("IdCanton")
                        .HasColumnType("int")
                        .HasColumnName("Country sub-entity identification code");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("City name");

                    b.HasKey("Id");

                    b.HasIndex("IdCanton");

                    b.ToTable("Distritos", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProfesional")
                        .HasColumnType("int");

                    b.Property<string>("IdTipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("IdentificationScheme.Identifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Master data party name");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Master data party identifier");

                    b.HasKey("Id");

                    b.HasIndex("IdProfesional");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Establecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadPrimaria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActividadSecundaria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoEstablecimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstablecimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCvo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Establecimientos", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.EstadoExcepcionMorosidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadosExcepcionesMorosidad", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.ExcepcionMorosidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("Document effective date/time");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Document expiration date/time");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegimen")
                        .HasColumnType("int");

                    b.Property<int>("IdSubtipoTramite")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoAccion")
                        .HasColumnType("int")
                        .HasColumnName("Additional statement code");

                    b.Property<int>("IdTipoTramite")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Master data party name");

                    b.Property<string>("NumeroIdentificacionEmpresa")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Additional identifier");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Additional statement description");

                    b.Property<string>("TipoIdentificacionEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Role code");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoAccion");

                    b.ToTable("ExcepcionesMorosidad", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Commodity category code");

                    b.HasKey("Id");

                    b.ToTable("Familias", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Imagenes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Id");

                    b.ToTable("Imagenes", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Monedas", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.NoticiasVuce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Enlace")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoIngles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TituloIngles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NoticiasVuce", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoA2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("CodigoC3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CountryCodeC3");

                    b.Property<string>("CodigoNumerico")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CountryCodeN3");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CountryName");

                    b.HasKey("Id");

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.PaisBloqueComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBloqueComercial")
                        .HasColumnType("int")
                        .HasColumnName("IdBloqueComercialPaisId");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("IdPais");

                    b.HasKey("Id");

                    b.ToTable("PaisBloqueComercial", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.ProductoRequisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRequisito")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdRequisito");

                    b.HasIndex("IdTipoProducto");

                    b.ToTable("ProductoRequisito", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Clase");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreCientifico");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreComun");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Presentacion");

                    b.Property<bool>("Tradicional")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdInterno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoRegente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Identifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Communication identifier");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("IdTipoIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ID.IdentificationScheme.Identifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ID");

                    b.Property<string>("Profesion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Role code");

                    b.HasKey("Id");

                    b.ToTable("Profesionales", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Country sub-entity name-CP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Country sub-entity name");

                    b.HasKey("Id");

                    b.ToTable("Provincias", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Requisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Additional statement description");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int")
                        .HasColumnName("Responsible government agency identifier");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("Destination Country name");

                    b.Property<string>("ImagenRequisito")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Binary file type code");

                    b.Property<string>("NombreImagenRequisito")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Additional statement description-V");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Requisitos", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sectores", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Sustancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Commodity characteristics description");

                    b.Property<string>("ListaCaq")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Commodity characteristic code");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Commodity characteristics description-Name");

                    b.HasKey("Id");

                    b.ToTable("Sustancias", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.SustanciaControlada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClasificacionArancelaria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HSClassification");

                    b.Property<string>("ClasificacionAshrae")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Commodity characteristic code");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("int")
                        .HasColumnName("Commodity category code");

                    b.Property<string>("PotencialCalentamientoGlobal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Additional statement description");

                    b.Property<string>("TipoGas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Commodity characteristics description");

                    b.HasKey("Id");

                    b.HasIndex("IdFamilia");

                    b.ToTable("SustanciaControlada", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoTarifa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionTarifa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("int");

                    b.Property<int>("IdServicioPlataforma")
                        .HasColumnType("int");

                    b.Property<int>("IdTarifa")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoServicioPlataforma")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServicioPlataforma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoServicioPlataforma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTarifa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdMoneda");

                    b.ToTable("Tarifas", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.TipoAccionExcepcionMorosidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposAccionesExcepcionesMorosidad", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.TipoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("Intended use statement");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int")
                        .HasColumnName("Responsible government agency identifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Commodity category code");

                    b.HasKey("Id");

                    b.ToTable("TipoProductos", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Variedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("Commodity characteristic code");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Commodity characteristics description");

                    b.HasKey("Id");

                    b.ToTable("Variedades", (string)null);
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Barrio", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Distrito", "Distrito")
                        .WithMany("Barrios")
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Canton", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Provincia", "Provincia")
                        .WithMany("Cantones")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.CaracteristicaTipoProducto", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Caracteristica", "Caracteristica")
                        .WithMany("CaracteristicaTipoProductos")
                        .HasForeignKey("IdCaracteristica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.TipoProducto", "TipoProducto")
                        .WithMany("CaracteristicaTipoProductos")
                        .HasForeignKey("IdTipoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.CatalogoInstitucion", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Catalogo", null)
                        .WithMany("CatalogoInstituciones")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Cultivo", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Variedad", "Variedad")
                        .WithMany("Cultivos")
                        .HasForeignKey("IdVariedad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Variedad");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Distrito", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Canton", "Canton")
                        .WithMany("Distritos")
                        .HasForeignKey("IdCanton")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Empresa", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Profesional", "Profesional")
                        .WithMany("Empresas")
                        .HasForeignKey("IdProfesional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.ExcepcionMorosidad", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.EstadoExcepcionMorosidad", "EstadoExcepcionMorosidad")
                        .WithMany("ExcepcionesMorosidad")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.TipoAccionExcepcionMorosidad", "TipoAccionExcepcionMorosidad")
                        .WithMany("ExcepcionesMorosidad")
                        .HasForeignKey("IdTipoAccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoExcepcionMorosidad");

                    b.Navigation("TipoAccionExcepcionMorosidad");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.ProductoRequisito", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Requisito", "Requisito")
                        .WithMany("ProductoRequisito")
                        .HasForeignKey("IdRequisito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.TipoProducto", "TipoProducto")
                        .WithMany("ProductoRequisito")
                        .HasForeignKey("IdTipoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisito");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Requisito", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Pais", "Pais")
                        .WithMany("Requisitos")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.SustanciaControlada", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Familia", "Familia")
                        .WithMany("SustanciaControlada")
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Tarifa", b =>
                {
                    b.HasOne("VUCE3.Catalogos.Dominio.Entidades.Moneda", "Moneda")
                        .WithMany("Tarifas")
                        .HasForeignKey("IdMoneda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Canton", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Caracteristica", b =>
                {
                    b.Navigation("CaracteristicaTipoProductos");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Catalogo", b =>
                {
                    b.Navigation("CatalogoInstituciones");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Distrito", b =>
                {
                    b.Navigation("Barrios");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.EstadoExcepcionMorosidad", b =>
                {
                    b.Navigation("ExcepcionesMorosidad");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Familia", b =>
                {
                    b.Navigation("SustanciaControlada");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Moneda", b =>
                {
                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Pais", b =>
                {
                    b.Navigation("Requisitos");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Profesional", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Provincia", b =>
                {
                    b.Navigation("Cantones");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Requisito", b =>
                {
                    b.Navigation("ProductoRequisito");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.TipoAccionExcepcionMorosidad", b =>
                {
                    b.Navigation("ExcepcionesMorosidad");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.TipoProducto", b =>
                {
                    b.Navigation("CaracteristicaTipoProductos");

                    b.Navigation("ProductoRequisito");
                });

            modelBuilder.Entity("VUCE3.Catalogos.Dominio.Entidades.Variedad", b =>
                {
                    b.Navigation("Cultivos");
                });
#pragma warning restore 612, 618
        }
    }
}
